targets:
  $default:
    builders:
      drift_dev:
        options:
          # Use the recommended new-style queries
          sql:
            dialect: sqlite
            options:
              version: "3.39"
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: none
